---
title: Human papillomavirus vaccines:_WHO position paper,_May 2017
author: Shiqiang Jiang
date: '2019-05-12'
slug: human-papillomavirus-vaccines-who-position-paper-may-2017
categories: []
tags: []
anchor: 2019-05-12-human-papillomavirus-vaccines-who-position-paper-may-2017
weight: 20
---

Human papillomavirus vaccines: WHO position paper, May 2017

Introduction
In accordance with its mandate to provide guidance to Member States on health policy matters, WHO issues a series of regularly updated position papers on vaccines and vaccine combinations against diseases that have an international public health impact. These papers are concerned primarily with the use of vaccines in large-scale immunization programmes. They summarize essential background information on the respective diseases and vaccines, and conclude with the current WHO position concerning their use in the global context.
The papers are reviewed by external experts and WHO staff, and reviewed and endorsed by the WHO Strategic Advisory Group of Experts (SAGE) on immuniza- tion (http://www.who.int/immunization/ sage/en/). The GRADE methodology is used to systematically assess the quality of available evidence. The SAGE decision- making process is reflected in the evidence-to-recommendation table.1 A description of the process followed for the development of vaccine position papers is available at: http://www.who.int/immuni- zation/position_papers/position_paper_ process.pdf.
The position papers are intended for use mainly by national public health officials and managers of immunization programmes. They may also be of interest to international funding agencies, vaccine advisory groups, vaccine manufacturers, the medical community, scientific media and the general public.
This document replaces the 2014 WHO position paper on vaccines against diseases caused by human papil- lomaviruses (HPV).2 It focuses primarily on the preven- tion of cervical cancer, but also considers the broader spectrum of cancers and other diseases preventable by HPV vaccination. It incorporates recent developments concerning HPV vaccines, including the licensure of a nonavalent (9-valent) vaccine and recent data on vaccine effectiveness, and provides guidance on the choice of vaccine. New recommendations are proposed regarding vaccination strategies targeting girls only or both girls and boys, and vaccination of multiple birth cohorts.3 These recommendations were discussed by SAGE in October 2016.4 Evidence presented at the SAGE meeting can be accessed at: http://www.who.int/immunization/ sage/meetings/2016/october/en/.

